export const HALLS_LISTS_REQUESTS = "HALLS_LISTS_REQUESTS"
export const HALLS_LISTS_SUCCESS = "HALLS_LISTS_SUCCESS"
export const HALLS_LISTS_FAIL = "HALLS_LISTS_FAIL"


export const HALLS_DETAILS_REQUESTS = "HALLS_DETAILS_REQUESTS"
export const HALLS_DETAILS_SUCCESS = "HALLS_DETAILS_SUCCESS"
export const HALLS_DETAILS_FAIL = "HALLS_DETAILS_FAIL"


export const HALL_CREATE_REQUEST = 'HALL_CREATE_REQUEST';
export const HALL_CREATE_SUCCESS = 'HALL_CREATE_SUCCESS';
export const HALL_CREATE_FAIL = 'HALL_CREATE_FAIL';
export const HALL_CREATE_RESET = 'HALL_CREATE_RESET';


export const HALL_UPDATE_REQUEST = ' HALL_UPDATE_REQUEST';
export const HALL_UPDATE_SUCCESS = 'HALL_UPDATE_SUCCESS';
export const HALL_UPDATE_FAIL = 'HALL_UPDATE_FAIL';
export const HALL_UPDATE_RESET = 'HALL_UPDATE_RESET';


export const HALL_DELETE_REQUEST = 'HALL_DELETE_REQUEST';
export const HALL_DELETE_SUCCESS = 'HALL_DELETE_SUCCESS';
export const HALL_DELETE_FAIL =    'HALL_DELETE_FAIL';
export const HALL_DELETE_RESET =   'HALL_DELETE_RESET';


export const HALL_REVIEW_CREATE_REQUEST = 'HALL_REVIEW_CREATE_REQUEST';
export const HALL_REVIEW_CREATE_SUCCESS = 'HALL_REVIEW_CREATE_SUCCESS';
export const HALL_REVIEW_CREATE_FAIL =    'HALL_REVIEW_CREATE_FAIL';
export const HALL_REVIEW_CREATE_RESET =   'HALL_REVIEW_CREATE_RESET';
// export default HALLS_LISTS_REQUESTS
// export default HALLS_LISTS_SUCCESS
// export default HALLS_LISTS_FAIL